name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'trihelm-node-react/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

# All shell steps run from the app subfolder
defaults:
  run:
    working-directory: horizon-node-react

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Optional debug: shows folders so you can verify the path
      - name: Debug workspace
        run: |
          pwd
          ls -la
          ls -la ..

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build
        run: npm run build

      - name: SPA fallback (copy index -> 404)
        run: cp dist/index.html dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # NOTE: repo-root relative path here
          path: horizon-node-react/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
