name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - '<SUBDIR>/horizon-node-react'      # only run when that folder changes
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

# Set the default working dir for all run: steps
defaults:
  run:
    working-directory: <SUBDIR>

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install
        # use `npm ci` if you commit a package-lock.json

      - name: Build
        run: npm run build

      # SPA fallback so client-side routes work on refresh
      - name: Add SPA fallback
        run: cp dist/index.html dist/404.html

      - name: Upload artifact (dist)
        uses: actions/upload-pages-artifact@v3
        with:
          path: <SUBDIR>/dist    # note: path is repo-root relative

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
